version: "3.8"

services:
  app:
    container_name: cloud-run-playground-app
    build: 
      context: ./app
    ports:
      - "8000:8000"
    command: uvicorn main:app --reload --host 0.0.0.0
    volumes:
      - ./app:/app
