tfc_organization_name = "Doarakko"
tfc_workspace_name    = "cloud-run-playground"
gcp_project_id        = "cloud-run-playground-379503"
gcp_region            = "asia-northeast1"
gh_repo_name          = "Doarakko/cloud-run-playground"
